# Generated by Django 2.1.7 on 2019-03-31 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='RipUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('real_name', models.CharField(max_length=20, verbose_name='real_name')),
                ('student_id', models.CharField(default='B000000', max_length=8, verbose_name='student_id')),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='username')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'rip_user',
                'default_permissions': (),
            },
        ),
        migrations.AddIndex(
            model_name='ripuser',
            index=models.Index(fields=['student_id'], name='rip_user_student_2584e9_idx'),
        ),
        migrations.AddIndex(
            model_name='ripuser',
            index=models.Index(fields=['email'], name='rip_user_email_e8dfc6_idx'),
        ),
        migrations.AddIndex(
            model_name='ripuser',
            index=models.Index(fields=['username'], name='rip_user_usernam_4062e0_idx'),
        ),
    ]
